# Service registers under this name
# Control the InternalResourceViewResolver:
spring:
  application:
    name: View-Service
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
server:
  port: 8787
  
